const partOne = [
  'display',
  'flex',
  'flex-direction',
  'justify-content',
  'justify-items',
  'justify-self',
  'align-content',
  'align-items',
  'align-self',
  'order',
  'flex-basis',
  'flex-flow',
  'flex-grow',
  'flex-shrink',
  'flex-wrap',
  'grid',
  'grid-area',
  'grid-auto-rows',
  'grid-auto-columns',
  'grid-auto-flow',
  'grid-gap',
  'grid-row',
  'grid-row-start',
  'grid-row-end',
  'grid-row-gap',
  'grid-column',
  'grid-column-start',
  'grid-column-end',
  'grid-column-gap',
  'grid-template',
  'grid-template-areas',
  'grid-template-rows',
  'grid-template-columns',
  'gap',
  'float',
  'clear',
  'box-sizing',
];

const partTwo = ['object-fit', 'object-position', 'overflow', 'overflow-x', 'overflow-y'];

module.exports = [...partOne, ...partTwo];
